replicaCount: 1

image:
  repository: astroband/stellar-parallel-catchup
  tag: master-009cdf42fdb0cef4070ac19fb34aefccbf46c3f2
  pullPolicy: IfNotPresent

database:
  url: postgres://localhost/stellar
  #
  # fromSecret:
  #   name: stellar-parallel-catchup
  #   key: database-url

ledger:
  min: 1
  # max: Must be set

parallelism:
  chunk: 1000
  concurrency: 3

persistence:
  # existingClaim:
  accessMode: ReadWriteOnce
  size: 8Gi
  subPath: "stellar-parallel-catchup"
  mountPath: "/data"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
